//========= Copyright (c) 1996-2002, Valve LLC, All rights reserved. ============
//
// Purpose: 
//
// $NoKeywords: $
//=============================================================================

#pragma once
#if !defined ( EV_HLDMH )
#define EV_HLDMH

// bullet types
typedef	enum
{
	BULLET_NONE = 0,
	BULLET_PLAYER_AK47, //AK47, G3SG1
	BULLET_PLAYER_AUG, //Galil, FAMAS, M4A1, Aug
	BULLET_PLAYER_SG552, //SG552, M249
	BULLET_PLAYER_P90, //P90, FiveseveN
	BULLET_PLAYER_AWP, //AWP
	BULLET_PLAYER_SCOUT, //Scout
	BULLET_PLAYER_G3SG1, //G3SG1
	BULLET_PLAYER_GLOCK, //Glock18, TMP
	BULLET_PLAYER_MP5N, //Elites, MP5
	BULLET_PLAYER_USP, //USP, Mac 10, UMP.45
	BULLET_PLAYER_DE, //DEagle
	BULLET_PLAYER_KNIFE,
	BULLET_PLAYER_XM1014, //XM1014, M3
	BULLET_PLAYER_SG550, //SG550
	BULLET_PLAYER_P228, //P228
	BULLET_PLAYER_ULTIMATE, //Ultimate goodness

	BULLET_PLAYER_357, // python
	BULLET_PLAYER_BUCKSHOT, // shotgun
	BULLET_PLAYER_CROWBAR, // crowbar swipe

	BULLET_MONSTER_9MM,
	BULLET_MONSTER_MP5,
	//Haunter
	BULLET_MONSTER_M249,
	BULLET_MONSTER_USP,
	BULLET_MONSTER_BUCKSHOT,
	BULLET_MONSTER_SENTRY,
	BULLET_MONSTER_TURRET,
	BULLET_MONSTER_APACHE,
	//Haunter
	BULLET_MONSTER_12MM
}Bullet;

//Haunter
enum usp_e
{
	USP_SIDLE = 0,
	USP_SSHOOT,
	USP_SSHOOT2,
	USP_SSHOOT3,
	USP_SSHOOTLAST,
	USP_SRELOAD,
	USP_SDRAW,
	USP_ADD_SILENCER,
	USP_IDLE,
	USP_SHOOT,
	USP_SHOOT2,
	USP_SHOOT3,
	USP_SHOOTLAST,
	USP_RELOAD,
	USP_DRAW,
	USP_REMOVE_SILENCER,
};

enum glock18_e
{
	GLOCK18_IDLE1 = 0,
	GLOCK18_IDLE2,
	GLOCK18_IDLE3,
	GLOCK18_SHOOT,
	GLOCK18_SHOOT2,
	GLOCK18_SHOOT3,
	GLOCK18_SHOOT_EMPTY,
	GLOCK18_RELOAD,
	GLOCK18_DRAW,
	GLOCK18_HOLSTER,
	GLOCK18_ADD_SILENCER,
	GLOCK18_DRAW2,
	GLOCK18_RELOAD2,
};

enum elite_e
{
	ELITE_IDLE = 0,
	ELITE_IDLE_LEFTEMPTY,
	ELITE_SHOOT_LEFT1,
	ELITE_SHOOT_LEFT2,
	ELITE_SHOOT_LEFT3,
	ELITE_SHOOT_LEFT4,
	ELITE_SHOOT_LEFT5,
	ELITE_SHOOT_LEFTLAST,
	ELITE_SHOOT_RIGHT1,
	ELITE_SHOOT_RIGHT2,
	ELITE_SHOOT_RIGHT3,
	ELITE_SHOOT_RIGHT4,
	ELITE_SHOOT_RIGHT5,
	ELITE_SHOOT_RIGHTLAST,
	ELITE_RELOAD,
	ELITE_DRAW,
};

enum fiveseven_e
{
	FIVESEVEN_IDLE1 = 0,
	FIVESEVEN_SHOOT1,
	FIVESEVEN_SHOOT2,
	FIVESEVEN_SHOOT_EMPTY,
	FIVESEVEN_RELOAD,
	FIVESEVEN_DRAW,
};

enum deagle_e
{
	DEAGLE_IDLE1 = 0,
	DEAGLE_SHOOT1,
	DEAGLE_SHOOT2,
	DEAGLE_SHOOT_EMPTY,
	DEAGLE_RELOAD,
	DEAGLE_DRAW,
};

enum p228_e
{
	P228_IDLE = 0,
	P228_SHOOT1,
	P228_SHOOT2,
	P228_SHOOT3,
	P228_SHOOT_EMPTY,
	P228_RELOAD,
	P228_DRAW,
};

enum m3_e
{
	M3_IDLE = 0,
	M3_SHOOT1,
	M3_SHOOT2,
	M3_INSERT,
	M3_AFTER_RELOAD,
	M3_START_RELOAD,
	M3_DRAW,
};

enum xm1014_e
{
	XM1014_IDLE = 0,
	XM1014_FIRE1,
	XM1014_FIRE2,
	XM1014_INSERT,
	XM1014_AFTER_RELOAD,
	XM1014_START_RELOAD,
	XM1014_DRAW,
};

enum mp5_e
{
	MP5N_IDLE1 = 0,
	MP5N_RELOAD,
	MP5N_DRAW,
	MP5N_SHOOT1,
	MP5N_SHOOT2,
	MP5N_SHOOT3,
};

enum tmp_e
{
	TMP_IDLE1 = 0,
	TMP_RELOAD,
	TMP_DRAW,
	TMP_SHOOT1,
	TMP_SHOOT2,
	TMP_SHOOT3
};

enum p90_e
{
	P90_IDLE1 = 0,
	P90_RELOAD,
	P90_DRAW,
	P90_SHOOT1,
	P90_SHOOT2,
	P90_SHOOT3
};

enum mac10_e
{
	MAC10_IDLE1 = 0,
	MAC10_RELOAD,
	MAC10_DRAW,
	MAC10_SHOOT1,
	MAC10_SHOOT2,
	MAC10_SHOOT3
};

enum ump45_e
{
	UMP45_IDLE1 = 0,
	UMP45_RELOAD,
	UMP45_DRAW,
	UMP45_SHOOT1,
	UMP45_SHOOT2,
	UMP45_SHOOT3
};

enum ak47_e
{
	AK47_IDLE1 = 0,
	AK47_RELOAD,
	AK47_DRAW,
	AK47_SHOOT1,
	AK47_SHOOT2,
	AK47_SHOOT3
};

enum m4a1_e
{
	M4A1_SIDLE = 0,
	M4A1_SSHOOT1,
	M4A1_SSHOOT2,
	M4A1_SSHOOT3,
	M4A1_SRELOAD,
	M4A1_SDRAW,
	M4A1_ADD_SILENCER,
	M4A1_IDLE,
	M4A1_SHOOT1,
	M4A1_SHOOT2,
	M4A1_SHOOT3,
	M4A1_RELOAD,
	M4A1_DRAW,
	M4A1_REMOVE_SILENCER,
};

enum sg552_e
{
	SG552_IDLE1 = 0,
	SG552_RELOAD,
	SG552_DRAW,
	SG552_SHOOT1,
	SG552_SHOOT2,
	SG552_SHOOT3
};

enum aug_e
{
	AUG_IDLE1 = 0,
	AUG_RELOAD,
	AUG_DRAW,
	AUG_SHOOT1,
	AUG_SHOOT2,
	AUG_SHOOT3
};

enum famas_e
{
	FAMAS_IDLE1 = 0,
	FAMAS_RELOAD,
	FAMAS_DRAW,
	FAMAS_SHOOT1,
	FAMAS_SHOOT2,
	FAMAS_SHOOT3
};

enum Galil_e
{
	GALIL_IDLE1 = 0,
	GALIL_RELOAD,
	GALIL_DRAW,
	GALIL_SHOOT1,
	GALIL_SHOOT2,
	GALIL_SHOOT3
};

enum awp_e
{
	AWP_IDLE = 0,
	AWP_SHOOT1,
	AWP_SHOOT2,
	AWP_SHOOT3,
	AWP_RELOAD,
	AWP_DRAW,
};

enum scout_e
{
	SCOUT_IDLE = 0,
	SCOUT_SHOOT,
	SCOUT_SHOOT2,
	SCOUT_RELOAD,
	SCOUT_DRAW,
};

enum g3sg1_e
{
	G3SG1_IDLE = 0,
	G3SG1_SHOOT,
	G3SG1_SHOOT2,
	G3SG1_RELOAD,
	G3SG1_DRAW,
};

enum sg550_e
{
	SG550_IDLE1 = 0,
	SG550_SHOOT,
	SG550_SHOOT2,
	SG550_RELOAD,
	SG550_DRAW,
};

enum m249_e
{
	M249_IDLE1 = 0,
	M249_SHOOT1,
	M249_SHOOT2,
	M249_RELOAD,
	M249_DRAW,
};

enum ultimate_e
{
	ULTI_JUSIDLE = 0,
	ULTI_JUSSHOOT1,
	ULTI_JUSSHOOT2,
	ULTI_JUSSHOOT3,
	ULTI_JUSRELOAD,
	ULTI_JUSDRAW,
	ULTI_JUSTICE,
	ULTI_JUDIDLE,
	ULTI_JUDSHOOT1,
	ULTI_JUDSHOOT2,
	ULTI_JUDSHOOT3,
	ULTI_JUDRELOAD,
	ULTI_JUDDRAW,
	ULTI_JUDGMENT,
};
//Haunter

enum shotgun_e
{
	SHOTGUN_IDLE = 0,
	SHOTGUN_FIRE,
	SHOTGUN_FIRE2,
	SHOTGUN_RELOAD,
	SHOTGUN_PUMP,
	SHOTGUN_START_RELOAD,
	SHOTGUN_DRAW,
	SHOTGUN_HOLSTER,
	SHOTGUN_IDLE4,
	SHOTGUN_IDLE_DEEP
};

#define	GAUSS_PRIMARY_CHARGE_VOLUME	256// how loud gauss is while charging
#define GAUSS_PRIMARY_FIRE_VOLUME	450// how loud gauss is when discharged

enum gauss_e
{
	GAUSS_IDLE = 0,
	GAUSS_IDLE2,
	GAUSS_FIDGET,
	GAUSS_SPINUP,
	GAUSS_SPIN,
	GAUSS_FIRE,
	GAUSS_FIRE2,
	GAUSS_HOLSTER,
	GAUSS_DRAW
};

void EV_HLDM_GunshotDecalTrace( pmtrace_t *pTrace, char *decalName );
void EV_HLDM_DecalGunshot( pmtrace_t *pTrace, int iBulletType );
//Haunter
void EV_HLDM_SmokePuff( pmtrace_t *pTrace, float *vecSrc, float *vecEnd );
void EV_HLDM_DecalGunshotPlayer( pmtrace_t *pTrace, int iBulletType );
void EV_HLDM_MuzzleFlash( vec3_t pos, float amount );
//Haunter
int EV_HLDM_CheckTracer( int idx, float *vecSrc, float *end, float *forward, float *right, int iBulletType, int iTracerFreq, int *tracerCount );
void EV_HLDM_FireBullets( int idx, float *forward, float *right, float *up, int cShots, float *vecSrc, float *vecDirShooting, float flDistance, int iBulletType, int iTracerFreq, int *tracerCount, float flSpreadX, float flSpreadY );
#endif // EV_HLDMH
